name: CI
on:
    push:
    pull_request:
        branches: [main]

jobs:
    basic-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 21.x
                  cache: 'npm'
            - run: npm ci
            - run: make lint
            - name: Generate coverage
              run: ./node_modules/.bin/c8 --config=./.c8rc.coveralls.json npm test
              env:
                  NODE_OPTIONS: '--enable-source-maps --no-warnings=ExperimentalWarning --loader ts-node/esm'
            - name: Coveralls GitHub Action
              uses: coverallsapp/github-action@v2.2.3
              with:
                  file: './coverage/lcov.info'
